# Generated by Django 5.0.3 on 2024-04-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
