# Generated by Django 5.0.3 on 2024-04-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userdetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='zipcode',
            field=models.BigIntegerField(null=True),
        ),
    ]
