# Generated by Django 5.0.3 on 2024-04-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userdetails_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
