# Generated by Django 5.0.3 on 2024-04-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='C_description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='description',
            new_name='P_description',
        ),
    ]
