# Generated by Django 5.0.3 on 2024-04-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_description_category_c_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categorys',
            new_name='categorys_m',
        ),
    ]
